name: Docker Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Execute tests
        uses: joonvena/robotframework-docker-action@main
        with:
          robot_tests_dir: ./tests/data_driven_tests.robot
          robot_options: '-d ./reports'
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: ./reports

  generate_report:
    if: always()
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@main
        with:
          gh_access_token: ${{ secrets.PAT }}